<a href="https://colab.research.google.com/github/Bardala/PyTorch-for-Deep-Learning-Machine-Learning/blob/main/pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals
Resources: https://www.learnpytorch.io/00_pytorch_fundamentals/

## Discussion
If you have a question:
https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.0.1+cu118


# Introduction to Tensors
## Creating Tensors
PyTorch tensors are created using ```torch.Tensor()``` = https://pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar
scalar = torch.tensor(9)
scalar

tensor(9)

In [ ]:
scalar.ndim

0

In [ ]:
print(scalar.item())
print(type(scalar.item()))

9
<class 'int'>


In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

The shape tells you how the elements inside them are arranged.

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
print(MATRIX.ndim)
MATRIX2 = torch.tensor([[1]])
print(MATRIX2.ndim)

2
2


I want to stress that tensors can represent almost anything.

In [ ]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
print(TENSOR.ndim)
print(TENSOR.shape)

3
torch.Size([1, 3, 3])


In [ ]:
TENSOR[0][0][0]

tensor(1)

#create my random tensor
import torch
radnom_tensor = torch.rand(size=(3,4))
torch.rand(4,5)

In [ ]:
tpl = (3,4)
random_tnsr = torch.rand(size=(3,4))
rdm = torch.rand(size=(3,4))
print(random_tnsr)
print(rdm)
print(rdm * torch.zeros(3,4))
print(torch.rand(tpl))

tensor([[0.1105, 0.1532, 0.7193, 0.0882],
        [0.9272, 0.3595, 0.4725, 0.1536],
        [0.5533, 0.5976, 0.8772, 0.6150]])
tensor([[0.6779, 0.8190, 0.8504, 0.5119],
        [0.7446, 0.3675, 0.4902, 0.8060],
        [0.9193, 0.1472, 0.4152, 0.9510]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0.9061, 0.0529, 0.1904, 0.6084],
        [0.9788, 0.0510, 0.2913, 0.4167],
        [0.9569, 0.1033, 0.5472, 0.2828]])


In [ ]:
tpl = (224, 224, 3)
img = torch.rand(size=tpl)
print(img.ndim)
print(img.shape)
print(img.shape)
print(img.dtype)


3
torch.Size([224, 224, 3])
torch.Size([224, 224, 3])
torch.float32


In [ ]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tnsr

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

**tensor**	an n-dimensional array of numbers	can be any number, a **0-dimension** tensor is a scalar, a **1-dimension** tensor is a vector

In [ ]:
zeros.dtype

torch.float32

# Create a range of tensors and tensors-like


In [ ]:
# Use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

<ipython-input-19-a404776195c1>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Train
rng = torch.arange(0,10,2)
print(rng)
z_t = torch.zeros_like(rng)
o_t = torch.ones_like(rng)
print(z_t)
print(o_t)

tensor([0, 2, 4, 6, 8])
tensor([0, 0, 0, 0, 0])
tensor([1, 1, 1, 1, 1])


# Tensor datatypes

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

# Getting information from tensors

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.0860, 0.9053, 0.2292, 0.8270],
        [0.9768, 0.0754, 0.2156, 0.9701],
        [0.6259, 0.1461, 0.8468, 0.4796]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu



Note: When you run into issues in PyTorch, it's very often one to do with one of the three attributes above. So when the error messages show up, sing yourself a little song called "what, what, where":

- "what shape are my tensors? what datatype are they and where are they stored? what shape, what datatype, where where where"

# Manipulating tensors (tensor operations)

In [ ]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
print(tensor + 10)
print(tensor * 10)
print(tensor - 10)
print(tensor / 10)

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])
tensor([0.1000, 0.2000, 0.3000])


In [ ]:
# Can also use torch functions
torch.multiply(tensor, 10)
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
print(torch.add(tensor, 10))
print(tensor * tensor)

tensor([11, 12, 13])
tensor([1, 4, 9])


# Matrix multiplication (is all you need)


PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

1. The inner **dimensions** must match:
- (3, 2) @ (3, 2) won't work
- (2, 3) @ (3, 2) will work
- (3, 2) @ (2, 3) will work

2. The resulting matrix has the shape of the outer dimensions:
- (2, 3) @ (3, 2) -> (2, 2)
- (3, 2) @ (2, 3) -> (3, 3)

Note: "@" in Python is the symbol for matrix multiplication.

In [ ]:
import torch
tensor = torch.tensor([1,2,3])
print(tensor.shape)
print(tensor.ndim)

torch.Size([3])
1


In [ ]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [ ]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 671 µs, sys: 0 ns, total: 671 µs
Wall time: 605 µs


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 24 µs, sys: 4 µs, total: 28 µs
Wall time: 31 µs


tensor(14)

# One of the most common errors in deep learning (shape errors)


In [ ]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

print(tensor_A.shape)
print(tensor_B.shape)
# torch.matmul(tensor_A, tensor_B) # (this will error)

torch.Size([3, 2])
torch.Size([3, 2])


## You can perform transposes in PyTorch using either:

- torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
- tensor.T - where tensor is the desired tensor to transpose.

In [ ]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])



You can also use torch.mm() which is a short for torch.matmul().

In [ ]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [ ]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2,
                         out_features=9)
x = tensor_A
out = linear(x)
print(out)

tensor([[ 1.3843,  1.3137, -0.1953,  0.4034, -0.7014,  1.3484,  0.1558, -0.1847,
          0.5545],
        [ 3.6393,  2.2815, -0.2198,  0.5454, -0.4922,  2.8423,  1.3921,  0.2975,
          1.8537],
        [ 5.8944,  3.2493, -0.2443,  0.6874, -0.2830,  4.3362,  2.6285,  0.7798,
          3.1529]], grad_fn=<AddmmBackward0>)


# Finding the min, max, mean, sum, etc (aggregation)

In [ ]:
tbl = (3,3)
tbl2 = (2,3)
tnsA = torch.arange(0,100,10)
tnsB = torch.rand(tbl)
tnsC = torch.rand(tbl2)

print('tnsA',tnsA ,'\n')
print('tnsB',tnsB,'\n')
print('tnsC',tnsC,'\n')

print(tnsA.min())
print(tnsB.max())
print(tnsB.mean())
# print(tnsA.mean()) # it won't work
print(tnsA.type(torch.float32).mean())
print(f'''{tnsC.sum()}
      ''')
print(f'''{tnsA.sum()}
      ''')

print(f"""index of the max value in tnsC = {tnsC.argmax()}
""")

print(f'''index of the min value in tsnA = {tnsA.argmin()}
''')

tnsA tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]) 

tnsB tensor([[0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090]]) 

tnsC tensor([[0.5779, 0.9040, 0.5547],
        [0.3423, 0.6343, 0.3644]]) 

tensor(0)
tensor(0.9516)
tensor(0.4884)
tensor(45.)
3.3776321411132812
      
450
      
index of the max value in tnsC = 1

index of the min value in tsnA = 0



# Change tensor datatype

See differant types
https://pytorch.org/docs/stable/tensors.html


In [ ]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
print(tensor.dtype, '\n')

# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
print(tensor_float16,'\n')

# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
print(tensor_int8,'\n')

t32 = tensor.type(torch.float)
print(t32,'\n')

t64 = tensor.type(torch.double)
print(t64,'\n')

cmp32 = tensor.type(torch.chalf)
print(cmp32,'\n')

torch.float32 

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16) 

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8) 

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.]) 

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float64) 

tensor([10.+0.j, 20.+0.j, 30.+0.j, 40.+0.j, 50.+0.j, 60.+0.j, 70.+0.j, 80.+0.j, 90.+0.j],
       dtype=torch.complex32) 



<ipython-input-40-c98a979efaff>:19: UserWarning: ComplexHalf support is experimental and many operators don't support it yet. (Triggered internally at ../aten/src/ATen/EmptyTensor.cpp:31.)
  cmp32 = tensor.type(torch.chalf)


# Reshaping, stacking, squeezing and unsqueezing

- torch.**reshape**(input, shape):	Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().
- torch.Tensor.**view**(shape):	Returns a view of the original tensor in a different shape but shares the same data as the original tensor.
- torch.**stack**(tensors, dim=0):	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.
- torch.**squeeze**(input):	Squeezes input to remove all the dimenions with value 1.
- torch.**unsqueeze**(input, dim):	Returns input with a dimension value of 1 added at dim.
- torch.**permute**(input, dims):	Returns a view of the original input with its dimensions permuted (rearranged) to dims.

In [ ]:
t = torch.arange(0, 10, 3)
print(t, '\n', t.shape)

reshaped_t = t.reshape(1,4)
print('\n',reshaped_t)

view = t.view(1,4)
print ('\n', view)

tensor([0, 3, 6, 9]) 
 torch.Size([4])

 tensor([[0, 3, 6, 9]])

 tensor([[0, 3, 6, 9]])


In [ ]:
# Changing view changes oringal tensor
view[:, 0] = 5
view, t

(tensor([[5, 3, 6, 9]]), tensor([5, 3, 6, 9]))

In [ ]:
stacked = torch.stack([t,t,t]) # dim=0 by default
print(stacked)

stacked = torch.stack([t,t], dim=1)
print(stacked)

stacked = torch.stack([t,t,t,t], dim=-2)
print(stacked)

tensor([[5, 3, 6, 9],
        [5, 3, 6, 9],
        [5, 3, 6, 9]])
tensor([[5, 5],
        [3, 3],
        [6, 6],
        [9, 9]])
tensor([[5, 3, 6, 9],
        [5, 3, 6, 9],
        [5, 3, 6, 9],
        [5, 3, 6, 9]])


In [ ]:
# to remove all single dimensions use squeeze(), to add a single dimension use unsqueeze()
t = torch.rand((1,3))
t, t.squeeze(), t.unsqueeze(dim=0)

(tensor([[0.7104, 0.9464, 0.7890]]),
 tensor([0.7104, 0.9464, 0.7890]),
 tensor([[[0.7104, 0.9464, 0.7890]]]))

In [ ]:
# use torch.permute to rearrange the order of axis values
# if you change the values in the view, it will change the values of the original.
tpl = (312, 233, 122)
t = torch.rand(tpl)
print(t.shape,'\n')

permuted = t.permute(2,0,1)
print(permuted.shape, '\n')


torch.Size([312, 233, 122]) 

torch.Size([122, 312, 233]) 



# Indexing (selecting data from tensors)

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
print(x, x.shape,'\n')

# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) torch.Size([1, 3, 3]) 

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [ ]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

# PyTorch tensors & NumPy

In [ ]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
f_32 = torch.from_numpy(array).type(torch.float)
f_32

tensor([1., 2., 3., 4., 5., 6., 7.])

In [ ]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

#Reproducibility (trying to take the random out of random)


In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.5171, 0.7149, 0.8168, 0.4533],
        [0.2111, 0.8753, 0.5897, 0.3591],
        [0.2747, 0.6359, 0.4608, 0.2443]])

Tensor B:
tensor([[0.0877, 0.7661, 0.4528, 0.1570],
        [0.7519, 0.3985, 0.6505, 0.6506],
        [0.2903, 0.1924, 0.7707, 0.7683]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [ ]:
tpl = (3,3)
randomSeed= 22
torch.random.manual_seed(randomSeed)
c = torch.rand(tpl)

torch.random.manual_seed(randomSeed)
d = torch.rand(tpl)

c, d, c == d

(tensor([[0.3659, 0.7025, 0.3104],
         [0.0097, 0.6577, 0.1947],
         [0.9506, 0.6887, 0.8174]]),
 tensor([[0.3659, 0.7025, 0.3104],
         [0.0097, 0.6577, 0.1947],
         [0.9506, 0.6887, 0.8174]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

# Running tensors on GPUs (and making faster computations)

## Putting tensors (and models) on the GPU

In [ ]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [ ]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

## 4. Moving tensors back to the CPU

In [ ]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
# tensor_on_gpu.numpy()

In [ ]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

# Exercies

## 2. Create a random tensor with shape (7, 7).

In [ ]:
import torch
tpl = (7,7)
rand = torch.rand(tpl)
rand.shape

torch.Size([7, 7])

## 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [ ]:
t2 = torch.rand((1,7))
res = torch.mm(t2, rand)
res.shape, res

(torch.Size([1, 7]),
 tensor([[1.0677, 1.3110, 1.9316, 1.6545, 1.2132, 1.0511, 1.4809]]))

## 4. Set the random seed to 0 and do 2 & 3 over again.

In [ ]:
seed = 0
torch.random.manual_seed(seed)
rand = torch.rand((7,7))

torch.random.manual_seed(seed)
t2 = torch.rand((1,7))

res = torch.mm(t2, rand)

rand, t2, res, res.shape

(tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]),
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]]),
 tensor([[1.4453, 1.0926, 1.4581, 1.3235, 1.4729, 1.2880, 0.7752]]),
 torch.Size([1, 7]))

## 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

- If there is, set the GPU random seed to 1234.


In [ ]:
seed = 1234
torch.cuda.manual_seed(seed)
rand = torch.rand((7,7))

torch.cuda.manual_seed(seed)
t2 = torch.rand((1,7))

res = torch.mm(t2, rand)

rand, t2, res, res.shape

(tensor([[0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783],
         [0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]]),
 tensor([[0.5932, 0.1123, 0.1535, 0.2417, 0.7262, 0.7011, 0.2038]]),
 tensor([[1.2811, 0.8212, 1.6371, 1.4238, 1.6102, 1.3649, 0.6326]]),
 torch.Size([1, 7]))

## 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

In [ ]:
# Check for GPU
import torch
torch.manual_seed(1234)
device = 'cuda' if torch.cuda.is_available() else 'cpu'

tpl = (2,3)
rand0 = torch.rand(tpl).to(device)
rand1 = torch.rand(tpl).to(device)

rand0, rand1

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

## 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [ ]:
mult = torch.mm(rand0, rand1.T)
mult

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

## 8. Find the maximum and minimum values of the output of 7.

In [ ]:
mult.max(), mult.min()

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

## 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
mult.argmax(), mult.argmin()

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

## 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [ ]:
tpl = (1,1,1,10)
seed = 7
torch.manual_seed(seed)

t1 = torch.rand(tpl)
t2 = t1.squeeze()

t1, t1.shape, t2, t2.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))